### ISSUE TITLE
Improvements to UI translations

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#1033]
# Context
When we released Spanish and French UI translations, people were super happy about it but also noticed some gaps/things to improve.
I'll document those suggestions in this issue.

# Spanish
Ivan:
* Library right now is translated to "Librería". In Spanish "Librería" is where you buy books. In IT terms the correct translation is "Biblioteca" [1], but in this case I would suggest  "Catálogo" [2]

* Dataset is translated to "Conjunto de datos" - is a long translation, and I was suggesting "Set de datos" that is a bit shorter. I don't have strong opinion on this one. Both terms have been used as valid translations to the term Dataset. World Bank's open data portal translates the term "Dataset" to "Bases de datos" which is also correct.

# French
How could we solve it?

# Missing translations

* Dataset filter in visualisaiton editor
<img width="374" alt="screen shot 2017-08-30 at 16 26 33" src="https://user-images.githubusercontent.com/21127166/29877515-1f88d994-8da0-11e7-98c1-5f7bcdedc781.png">

* When renaming a column, the 'Rename' button is not translated:
<img width="265" alt="screen shot 2017-08-30 at 16 21 55" src="https://user-images.githubusercontent.com/21127166/29877249-615db32c-8d9f-11e7-87a0-991f7931e25f.png">

* Visualisation type as shown in the library, e.g. map or pivot table:
<img width="297" alt="screen shot 2017-08-29 at 13 55 38" src="https://user-images.githubusercontent.com/21127166/29819670-ef2d538a-8cc1-11e7-886b-dcf895b9d590.png">

* Admin section
* Actions in Transformation log, e.g. 'deleted a column'
<img width="273" alt="screen shot 2017-08-30 at 16 22 54" src="https://user-images.githubusercontent.com/21127166/29877338-9b681616-8d9f-11e7-8588-fa7b32ca65ae.png">

* Map visualisation editor:

<img width="1181" alt="screen shot 2017-08-29 at 14 00 43" src="https://user-images.githubusercontent.com/21127166/29819802-8370d454-8cc2-11e7-8f91-12e807c989a0.png">

* Data type for columns in visualisations editor:

<img width="382" alt="screen shot 2017-08-29 at 14 01 36" src="https://user-images.githubusercontent.com/21127166/29819854-ac27d942-8cc2-11e7-91d2-49ce84fa2786.png">

* 'Untitled dashboard' and 'Untitled visualisation'

<img width="259" alt="screen shot 2017-08-29 at 14 04 50" src="https://user-images.githubusercontent.com/21127166/29819965-206e44da-8cc3-11e7-9bd7-097bc746e9aa.png">

**Comment by finnfiddle** [comment]
## TODO

### Spanish

- [ ] Library -> Catálogo
- [ ] Dataset -> Set de datos

### French

- [ ] Dataset filter in visualisaiton editor
- [ ] When renaming a column, the 'Rename' button is not translated:
- [ ] Visualisation type as shown in the library, e.g. map or pivot table:
- [ ] Admin section
- [ ] Actions in Transformation log, e.g. 'deleted a column'
- [ ] Map visualisation editor:
- [ ] Data type for columns in visualisations editor:
- [ ] 'Untitled dashboard' and 'Untitled visualisation'

**Comment by tangrammer** [comment]
@finnfiddle I don't know if in previous translations you keep technical terms like `geoshape` or `geopoint` ....
