### ISSUE TITLE
Add filters to dashboards 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#1656]
# Context
*Why do we add this issue?*

Dashboards hold multiple visualisations and text to showcase a situation of a project, tell a story, to showcase the situation on the ground to eventually drive decisions. 

# Problem 

You have a dataset for an entire country and create different visualisations. The dashboard holds these visualisations and you see the visualisations being based on the entire country. Then you want to see what the situation is in one region (a value in the dataset). So you select that region in your filter and the visualisations adjust to be based on the filtered out data. Or you want to see the status for all water points built by a specific organisation (another variable in the dataset). 

This is not possible today in Lumen. 

## Current status quo
Today users have to make a separate dashboard with the exact same visualisation for each district. However, for more than 10 districts making a dashboard for each separately is cumbersome and you loose overview in the bar graphs.

# Solution or next step

The idea is to be able to filter an existing dashboard. I view a shared dashboard and then select to show me the chart based on a certain variable. I expect the created visuals to adapt to my filter. 

Example holding open data: http://213.136.89.20/akvo/ethiopia-water-points-functionality/

**To keep in mind**: Filtering assumes you are working with one dataset. But in Lumen, you can create one dashboard that holds visualisations from many datasets or you only select visualisations from one dataset. 

Some initial sketches from 2017 can be found here: https://projects.invisionapp.com/share/9TCLA2ORF#/screens/243782421

**Comment by janagombitova** [comment]
I spoke with Irene today to understand a bit more on the use of dashboards with filters, what they expectations are, etc. 

* dashboards are used for monitoring a project and its impact and results. The filters would then help to see the differences and results per different regions that are part of the project, or for a specific timeframe, or component
* today, for example, she created three dashboards for Football for Water with the 'same' visuals per different area: 
   * https://footballforwater.akvolumen.org/dashboard/5d15d9c4-3550-4564-b49b-989676a78d69
   * https://footballforwater.akvolumen.org/dashboard/5d15d32f-a4af-47a8-a8ec-75e0c8d3c6c7
   * https://footballforwater.akvolumen.org/dashboard/5d14c364-97fd-45c8-b01e-44a064dcd835
* the person creating the dashboard is the one who will also decide on which columns the viewer can filter the visualisations on the shared dashboard 
* the expectation is that once the viewer selects her filter, the visualisation will adjust based on that data
* she noted that some visualisations might not fall under the filter, as they might come from another dataset and are in the dashboard to provide context. Then these visualisations should stay in view but Lumen should somehow indicate that the applied filter does not affect this and this visualisation
* most often dashboards are based on one dataset 
* in very rare cases, a dashboard holds visualisations from multiple datasets and in this case the selected filter would be from a column that all the datasets (that the visualisations are based on) have. Or the visuals will simply not filter (as mentioned in the point above)
* for the filters to be useful you need more than one filter, more that one column. But these columns do **not** relate. So you can have a filter based on column 'Project type', then on column 'Region' and another on 'Gender'. The viewer then decides she wants to see the dashboard visuals for Project type - Education, Region - North and Gender - Women

**Comment by janagombitova** [comment]
Notes form @Kiarii kiarii - from today's meeting: 
We agreed that Daniel will explore the most basic implementation - Adding 1 filter col of type text, handled as a dropdown - as a test drive version to see figure out how filters will work; I will provide wireframes accordingly.

**Comment by Kiarii** [comment]
After our call (Juan, Ivan, Daniel, Kiarii) we figured based on the insights provided by Irene + Lars, an MVP could feature 3 filtering cols, of type Text (with 'free text' cols being an exception), with dropdowns as filter handles on the dashboard with 'All' as the default values. 

The current [wireframe](https://invis.io/SYUXZT8EFRH#/393880064_0-_DB_-_Visualizations) also illustrate how we could notify users of visualizations that are not affected by applied filters

The following were questions that were left open;
- How to handle filter conflicts: e.g. when a visualization is filtered to a specific region and the 'region' column is applied as a dashboard filter
- How unique values may be used to remove 'free-text' cols as filtering cols candidates. We had mentioned the idea of using 10 - 15 unique values but we have to note that unique values in cascade questions could be in the hundreds
- How to handle pdf exporting of a filtered dashboard
- How to handle maps - is it sth we can easily do or does it require extra work in which case it is reserved for a future iteration?

**Comment by tangrammer** [comment]
- [ ] in this PR there are a few questions that should be answered https://github.com/akvo/akvo-lumen/pull/2516

**Comment by tangrammer** [comment]
- [ ]show dashboard objects affected when removing a dataset
- [ ] in relation to how loading column values in dashboard editor ... maybe we could follow `api/datasets/ds-id/sort/column-name/text` approach

**Comment by tangrammer** [comment]
- [] [send payload filter](https://github.com/akvo/akvo-lumen/pull/2525/commits/df9df3d070078444aa133e27a1b1744373e80bb2) spec to backend onChange filter column value
- [ ] add filter spec on addVisualisation click

**Comment by tangrammer** [comment]
- [ ] add filter to new viz added once the dasboard is loaded (the way that new vizs are aggregated is not the same as the full dashboard aggregations)
- [ ] don't apply filter if value is null [backend]

**Comment by tangrammer** [comment]
- [ ] if there is already a filter, load it on dashboard load

**Comment by Kiarii** [comment]
I test drovee the WIP on this epic on Mon, here are some notes from that:
- the basic application of dataset cols as dashboard filters work.
- It is possible to apply more than one cols -> not sure if we have addressed the concerns that we had about this when we embarked on the epic..

Still to do

- [ ] if more than one filter is applied, present these horizontally
- [ ] use "All" as the default filter text in place of "select.." since 
- [ ] Consider using “Visualizations filterable by selected dataset” as a mouseover tip on the 'n/x visualizations text' in place of what had been previously provided (hope the newer version makes sense)
<img width="381" alt="Screenshot 2020-02-03 at 11 51 42" src="https://user-images.githubusercontent.com/12692444/73829937-7bad8c00-480c-11ea-9b45-e5ca58672860.png">

- [ ] the 'Text' element should have a ‘+’ preceding it, and mouseover “insert text” 
- [ ] Style the field labels ‘Dataset and Filter’ Normal in place of Bold
- [ ] The filters tab Empty State should hint what the user can do there even before they get started..
<img width="366" alt="Screenshot 2020-02-03 at 12 01 46" src="https://user-images.githubusercontent.com/12692444/73830308-23c35500-480d-11ea-861f-19246f011266.png">

**Comment by tangrammer** [comment]
- [ ] review that map types are properly filtered
- [ ] review that public dashboards works as expected

**Comment by tangrammer** [comment]
- [ ] don't PUT dashboard if user change dashboard filter value

**Comment by tangrammer** [comment]
- [ ] exporting dashboard should export current filter value

**Comment by kardan** [comment]
- After slimming the visualisation call it's not expensive to grab all any longer. Therefore I suggest that we postpone limiting the number of visualisations to later if needed
- Regarding what to show for the dashboard filter selection on exports (the drop down or some more fancy text explaining the filter that is up for discussion)

**Comment by Kiarii** [comment]
Concerns / edge cases we have identified but will leave for later (quoting @kardan from Slack):

> in the exports is that we’re not showing what dataset is used for filtering. So in a multi layered map you would not be able to say what layer was filtered
> It’s a little odd that we have a filter on for example country and then another layer in the map can still show stuff in other countries

For now we will let the user resolve such conflicts.. We also hope to learn more through feedback and usage data once we have the first iteration out in the wild

**Comment by Kiarii** [comment]
Follow up notes and comments on today's test:
- Missing the (!) icon and accompanying mouseover text "Visualization will not be affected by set filters" on the dashboard editing side
- Missing the mouseover on the (!) icon; "Visualization not affected by applied filter" on the dashboard viewing side
- It is possible to select a filtering dataset for which there are 0/n visualizations that can be filtered by it, and apply filters to the dashboard. However, the added filters do not show on the viewed dashboard. I think we should show those

**Comment by tangrammer** [comment]
edited graphana query metrics, now working fine https://metrics.akvo.org/d/dd08npwWk/dashborad-filters-metrics?orgId=1

**Comment by kardan** [comment]
- [ ] reset/remove (!) icon filter flag upon removing filters in dashboard edit
- [ ] Add paddings
- [ ] Add mouseover text (Visualization not affected by applied filter)
