### ISSUE TITLE
Respect flow permissions

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#1950]
The long term goal is to integrate Flow and Lumen into a more unified user experience. As it is today they are different worlds and you import Flow forms into Lumen and get the data, but lose everything like context, permissions etc. Today a subset of users get access to Lumen, hence access to Lumen provides an authorization context where everything is available. However, we intend to open up Lumen use to all users of a Flow instance. With this in mind, we have to enforce permissions from Flow on data available in Lumen. 

- [x] filter library by using new Flow API authorization endpoint
- [x] [make sure all of the UI respect new permissions](https://github.com/akvo/akvo-lumen/issues/1951)
- [x] [make sure the public parts work as expected](https://github.com/akvo/akvo-lumen/issues/1950#issuecomment-485683468)
- [x] [put the new feature behind a feature flag to be exposed in sync with the Flow API endpoint](https://github.com/akvo/akvo-lumen/issues/1950#issuecomment-485682241). 

parent of #1949
parent of #1951

**Comment by kardan** [comment]
Since this feature will require some changes in Lumen and some in the Flow API (new endpoint) we should hide the feature behind a feature flag.

**Comment by kardan** [comment]
Related Flow API work 
https://github.com/akvo/akvo-flow-api/issues/146
https://github.com/akvo/akvo-flow-api/pull/147

**Comment by tangrammer** [comment]
- `put the new feature behind a feature flag to be exposed in sync with the Flow API endpoint `
just add `$auth$` to keycloak "first name" as following image shows ....
<img width="345" alt="Screen Shot 2019-04-22 at 18 06 26" src="https://user-images.githubusercontent.com/731829/56563602-61236280-65ac-11e9-8f26-d2cf1f5caf6a.png">

**Comment by tangrammer** [comment]
`- make sure the public parts work as expected`
Details on: 
- [akvo.lumen.lib.auth](https://github.com/akvo/akvo-lumen/blob/develop/backend/src/akvo/lumen/lib/auth.clj)
- [routing details that load auth-service data ](https://github.com/akvo/akvo-lumen/blob/develop/backend/src/akvo/lumen/lib/auth.clj#L86-L96)
- [example of using auth-service](https://github.com/akvo/akvo-lumen/blob/develop/backend/src/akvo/lumen/endpoint/dataset.clj#L17-L22)

**Comment by janagombitova** [comment]
I tested today on lumen.akvotest.org with two users with datasets coming from uat1.akvoflow.org. 
- User jana@akvo.org has full access to all Flow datasets on the Lumen and on Flow. 
- User akvo.flow.user.test@gmail.com has access to three folders on Flow UAT1, where to one folder the user has no data related permissions (only view and edit form permissions) 

Here are the steps I took and what I found: 
- on UAT1 Flow gave access to akvo.flow.user.test@gmail.com only three folders 
- on test Lumen with jana@akvo.org I imported the datasets from the three folders and created 2 visualisations for each dataset and two dashboards (one with all the visualisation the test user has access to and another with visualisations the test user does not have access to) 
- logged out with jana@akvo.org and logged in with the test user 
- via the user profile turned on the auth flag in the First name 
- reloaded the library of the test Lumen instance expecting to see the two datasets the user has access to and the visuals and dashboards 

Result: 
- test user can see all external datasets and visuals and dashboards 
- I cannot see anything coming from Flow, not even the two datasets I should see as I gave the user access to them before creating the datasets 
- initial Library loading is slow (takes a few seconds) and I saw we have a separate issue for this problem, but a visual cue (as the loading spinner) would help to show our users that Lumen is loading, be patient, rather than giving the impression that things are broken (empty Library)

**Comment by janagombitova** [comment]
We had a quick call with @tangrammer and @dlebrero today about the current status of things: 
- in Flow if a user only has form permissions but no data permissions, the user can still view data, so it is ok that she can also view and work with data in Lumen. We will have to resolve this in the future once we simplify the permissions 
- the test user now only sees the datasets he should see
- but the visualisations derived from the datasets he should see do not load, but should 
- the dashboards he should see do not work because visualisations do now load.

**Comment by tangrammer** [comment]
https://github.com/akvo/akvo-lumen/issues/1950#issuecomment-486169752 fixed by https://github.com/akvo/akvo-lumen/commit/82289aaf1a22498dfaee5a113d58b3ad5ab8049f

**Comment by janagombitova** [comment]
All the changes are now in production, hidden behind a feature flag. This is to monitor the API calls so we can understand how much strain the implementation creates and how much loading time we are facing for users when opening the library. 

We will monitor the situation for a period of time (to be agreed on with the team) and then decide if we can push the changes to users or we need to make other adjustments. Thus keeping this epic issue open.

**Comment by janagombitova** [comment]
Changes under this issue are complete. We have been tracking the performance and the latency data shows in some cases a rapid decrease in performance, more than 10s of initial loading time. We are now looking at ways how to speed up Flow's API. This work will be handled in a separate issue, thus this issue can be closed and considered done.
