### ISSUE TITLE
Release new dataset UI change outside of the RQG changes 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-lumen#2891]
Today @tangrammer and I spoke about the work on RQGs and what still needs to happen and how best to release all these changes with minimum disruption to users but also not creating more work on our end. We agreed we should release the UI changes to the dataset view - **the new data grid with data group side panel** as soon as possible regardless of the RQG work. 

This way users can adapt the new the UI and then the next change they will have to get used to will be having the RQG data.

With this issue, we should track the changes needed to make this happen. @tangrammer @marvinkome can you connect and involve others on this task? I expect we will need to adapt the Walkhtough text as well.

**Comment by janagombitova** [comment]
Today we agreed to: 
* release the data grid changes to all users with the walkthrough that does not need to be changed 
* add the option to opt-out for the users if they want to use the old design 

We still need to check that the implementation is ok, bug free and the data groups show consistently. I remember we had a few issues: https://github.com/akvo/akvo-lumen/issues/2760, https://github.com/akvo/akvo-lumen/issues/2741, https://github.com/akvo/akvo-lumen/issues/2756,  If they are resolved we should comment and close, if not handle them and check if there are not more.

Secondly, @kardan the opt-out should be something we remove after a period of time and the new UI is what all users have by default. I suggest 2 weeks. What do you think?

**Comment by janagombitova** [comment]
After testing the intro dialogue and the spotlight steps I would like to suggest the following changes to the text. 

## The benefits modal 
<img width="1218" alt="Screen Shot 2020-09-21 at 09 26 21" src="https://user-images.githubusercontent.com/12456965/93741424-af4af400-fbec-11ea-9e51-5656accb2c65.png">

We decided to follow this Atlassian design pattern. The current copy is however not engaging and only pointing out what has changed rather than why. Plus it holds one very long compound sentence. All points the benefits modal should avoid: https://www.atlassian.design/patterns/benefits-modal

**Suggested new copy:** 

Title: Experience the new dataset view

Text: 
Datasets are now split into data groups to make it easy to clean and transform your data. Get a better overview regardless of the side of the dataset. A dedicated data group holds all transformed columns to keep things organised. 

In the future, this new view will support data from repeated data groups and become the default.

## 1st spotlight 
<img width="1218" alt="Screen Shot 2020-09-21 at 09 26 40" src="https://user-images.githubusercontent.com/12456965/93741497-d275a380-fbec-11ea-890e-cfe005bcf192.png">

**Changes to the last sentence:** Lumen handles all data relations across the groups when transforming and visualising data. 

## 2nd spotlight 
<img width="1220" alt="Screen Shot 2020-09-21 at 09 26 53" src="https://user-images.githubusercontent.com/12456965/93741731-3f893900-fbed-11ea-8fff-76dfbe8a7d7e.png">

**Change to:** Select any data group to show its data on the grid.

**Comment by janagombitova** [comment]
Related issues but not showstoppers for the release (but need to be handled this week): 
* [ ] dataset does not expand to the full-screen width https://github.com/akvo/akvo-lumen/issues/2767
* [ ] when combining columns and generating geopoints in the new view I can only select columns from the selected group https://github.com/akvo/akvo-lumen/issues/2741
* [ ] order of the data groups is not correct when using transformation `split`
* [ ] order of the data groups does not match the order in the question groups in the Flow form https://github.com/akvo/akvo-lumen/issues/2756

**Comment by janagombitova** [comment]
Found a bug that we need to fix before releasing: If you `skip` the 1st screen in the walkthorugh- the benefits modal - and click on a data group, you get the benefits modal again. Same happens if you `skip` any of the following steps. I am using Chrome and an incognito window.

**Comment by janagombitova** [comment]
Released to all users
