### ISSUE TITLE
Error tracking with Sentry

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#677]
At the moment we don't have any insights in errors that happens for users. This makes it difficult to know if fixes are needed.

Implement error tracking using Sentry. Sentry is what other Akvo tools use and it makes sense to use that.

**Comment by kardan** [comment]
@jonase @gabemart @peeb  I made first steps on this. Exposing a "sentryDSN" key in the /env map for the client to use. But what do we want to do while in development? I guess we don't want to publish local development errors. Should the "sentryDSN" key return a specific value when we don't want to use Sentry or should we omit the key? I'm not sure what's best, thoughts?

**Comment by jonase** [comment]
@kardan On the client we have the `process.env.NODE_ENV` variable you can inspect, which will be `'production'` when we compile for production. 

```javascript
if (process.env.NODE_ENV === 'production') {
  Raven.config(sentryDSN).install();
  Raven.setExtraContext({ tenant })
}

// And later, when the user profile has loaded
if (process.env.NODE_ENV === 'production') {
  Raven.setUserContext(profile);
}

**Comment by kardan** [comment]
- [ ] Build /env endpoint
- [ ] Decide on a scheme to organise teams / projects which makes it easy to subscribe to the notifications one wants & also split on code bases. 
- [ ] Add secrets to akvo-config
- [ ] Update K8s cluster secrets (prod, dev)
- [ ] Update deployments (prod, test)
- [ ] Add Sentry suppor to the client
- [ ] Add Sentry support to the backend
