### ISSUE TITLE
Implement landing page backend

### ISSUE THREAD

**Issue by nadiagorchakova** [akvo/akvo-lumen#734]
# Problem or idea

Currently there is no landing page for Akvo Lumen. Users must know how to access a particular tenant. This is not particularly user-friendly.

# Solution or next step

Before frontend work is possible, a backend solution must be implemented.

Nginx needs to serve a static landing page at `(www.)akvolumen.org`, separate from the Lumen app which is accessed at `[tenant].akvolumen.org`. In addition to this, the local `webpack` development server needs to be reconfigured to allow for local development and testing of this landing page, on a separate URL, and our test and CI environments also need a way to access it.

## Tasks

- [x] Create placeholder template to generate basic landing page
- [x] Reconfigure `webpack` dev server to build and serve a new `index-landing.ejs` template on `www.lumen.localhost:3031`.
- [x] Configure Nginx to serve the generated landing page (on a different port, perhaps port 81).
- [ ] Configure GCP(?) to route correctly to this new page on `www.akvolumen.org`.
